# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37ff62ca7ef62bcfe5214fde1f3b7470c0eafe034b5b1388bdb619098f21bffe52952cceb494fb41b0aa68d20cb2ce1bf23b81e963a5e5d52f2473e09dbe493b

test:
  secret_key_base: 7161caf541e0cc49f540dd56704879b85d00a11dd188890355b96246ae30690d9c92c46e139f122f2609b853f88f99d1aeda5b4b6bd1f3dc559c6aa7d563e862

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
